### ISSUE TITLE
start button won't work

### ISSUE THREAD

**Issue by lebaneseplatter** [Runixe786/MD3-Windows#10]
whenever i click on the start button of the given taskbar, it just won't open. i tried reinstalling it but nothing worked.

**Comment by Runixe786** [comment]
Free/basic version is supposed to open windows default start menu and pro version is supposed to open custom material you start menu. Do mention which version of skin you are using and your windows version

**Comment by lebaneseplatter** [comment]
> Free/basic version is supposed to open windows default start menu and pro version is supposed to open custom material you start menu. Do mention which version of skin you are using and your windows version

i was in the basic version and thank you for seeing my problem
