### ISSUE TITLE
下载解压之后没有看到.rmskin文件

### ISSUE THREAD

**Issue by luban-130** [Runixe786/MD3-Windows#15]

**Comment by Runixe786** [comment]
Latest release is pro users only, you can't download if you haven't purchased it. For public version, check out 0.4 public beta release version and you can find rmskin file there.

**Comment by luban-130** [comment]
![1](https://github.com/user-attachments/assets/822d290a-660d-4f6f-91e6-ba2131470bbf)
依然没有.rmskin文件

**Comment by Runixe786** [comment]
![image](https://github.com/user-attachments/assets/b299fef2-cd3c-40d3-88e6-c5d128c0474c)

You can find direct download link for rmskin file by clicking on circled text.
