### ISSUE TITLE
Colors are strange

### ISSUE THREAD

**Issue by Zan1456** [Runixe786/MD3-Windows#2]
![image](https://github.com/user-attachments/assets/026d509d-ebca-44d6-9dd9-51c1df991e1a)

**Comment by Runixe786** [comment]
Looks like you didn't install the plugin, install it from here: https://github.com/Reallukeisbest/meterial-you/releases/tag/v1.0.0

Let me know if it's fine now

**Comment by Zan1456** [comment]
![image](https://github.com/user-attachments/assets/3d19d0bf-47c5-4a86-8829-31615728cd71)
