### ISSUE TITLE
The documents and other folders do not open as they are tied to your sahil/Document directory path

### ISSUE THREAD

**Issue by ANIKIT93** [Runixe786/MD3-Windows#3]
The Downloads, Documents and pictures pinned folders are hardcoded to your local path . Please see if they can be variables and ingested to your UI so the user can edit the path when adding the widget and you can dynamically update the widget variable files on load of the widget. If not possible then add a guide so that people can make manual changes and ingest in the changes.

**Comment by Runixe786** [comment]
Thanks for reporting, i am trying to find a universal fix for this so there is no need to edit anything. Hopefully by 0.4 or 0.5 it will be fixed. For now you can search this: "DownloadsBox" , "DocsBox" and "PicsBox" in the notepad while editing skin, and change the path in front of leftmouseupaction to your desired path. Please look the screenshot below for clarity of action, do the same for downloadsbox and docsbox
![Screenshot 2024-09-24 224951](https://github.com/user-attachments/assets/fc0584bb-8d2b-4eab-a7d6-342409d9bc3e)

**Comment by Runixe786** [comment]
This issue is fixed in 0.3-PublicBeta and closedbeta. Kindly check it out
