### ISSUE TITLE
where can we find the wallpaper?

### ISSUE THREAD

**Issue by abhi0-tech** [Runixe786/MD3-Windows#8]
need the wallpapers in the screenshots

**Comment by Runixe786** [comment]
Wallfever app on play store

**Comment by abhi0-tech** [comment]
> Wallfever app on play store

For pc?

**Comment by abhi0-tech** [comment]
> Wallfever app on play store

Can you just share the wallpapers you used in the preview?

**Comment by Runixe786** [comment]
They are paid and I don't own them, so I'm not authorised to distribute them.
