### ISSUE TITLE
Task Bar Widget

### ISSUE THREAD

**Issue by Ajay282515** [Runixe786/MD3-Windows#9]
I purchased the pro version today. When i select the taskbar widget it is not appearing on the screen . But when i toggle to the free version it is loading. Please help

**Comment by Runixe786** [comment]
Hello, can you tell me what's your device resolution and scale you have set from windows display settings. Also do join the private group to share these issues so I can address it better there

**Comment by Ajay282515** [comment]
1366 x 768
How to join the private group

**Comment by Runixe786** [comment]
DM me on telegram at t.me/MaybeSahil , i will share you the link there to discuss this issue.
